export const url = {
    
    groupItem: <string> "http://localhost/evendorAPI/groupsitem.php",
    userItems: <string> 'http://localhost/evendorAPI/userlist.php',
    userListForOrder: <string> "http://localhost/evendorAPI/userlistfororder.php",
    vendor: <string> "http://evendors.host/api/vendor",
    vendors: <string> "http://evendors.host/api/vendors",
    order1: <string> "http://localhost/evendorAPI/order.php",
    vendorNote: <string> "http://localhost/evendorAPI/vendornote.php",
    suspend1: <string> "http://localhost/evendorAPI/suspend.php",
    login: <string> "http://localhost/evendorAPI/login.php",
    signup: <string> "http://evendors.host/api/user",
    signin: <string> "http://evendors.host/api/user/signin",
    recipients: <string> "http://evendors.host/api/recipients",
    recipient: <string> "http://evendors.host/api/recipient",
    allitems: <string> "http://evendors.host/api/items/all",
    items: <string> "http://evendors.host/api/items",
    useritems: <string> "http://evendors.host/api/useritems",
    useritem: <string> "http://evendors.host/api/useritem",
    groups: <string> "http://evendors.host/api/groups",
    group: <string> "http://evendors.host/api/group",
    customitem: <string> "http://evendors.host/api/customitem",
    order: <string> "http://evendors.host/api/order",
    orders: <string> "http://evendors.host/api/orders",
    lastorders: <string> "http://evendors.host/api/lastorders",
    orderlist: <string> "http://evendors.host/api/orderlist",
    orderlistforupdate: <string> "http://evendors.host/api/orderlistforupdate",
    orderupdate: <string> "http://evendors.host/api/orderupdate",
    suspend: <string> "http://evendors.host/api/suspendedorder",
    itemsnote: <string> "http://evendors.host/api/itemsnote",
    accounts: <string> "http://evendors.host/api/accounts",
    passvalidation: <string> "http://evendors.host/api/passvalidation",
    loginedit: <string> "http://evendors.host/api/loginedit"
}